---
- name: Join cluster
  hosts: master
  
  tasks:

   - name: List kubeadm join command
     shell: kubeadm token create --print-join-command
     register: kubeadm_join

   - name: Set the fact
     set_fact:
      kubeadm_join: "{{ kubeadm_join }}"

- name: Join workers to master
  hosts: workers
  become: yes

  tasks:

  - name: Run kubeadm_join on workers
    debug:
     msg: "{{ hostvars[item]['kubeadm_join'].stdout }}"
    with_items: "{{ groups['master'] }}"