---
# Initializes master node for master group, worker nodes for worker group

# TODO add conditional execution to all command/shell/iptables/lineinfile calls
# TODO get non-idempotent vars out of here

- name: Join cluster
  hosts: master
  
  tasks:

   - name: Initialize master node
     command: kubeadm init --control-plane-endpoint "{{ hostvars[item]['ansible_eth0']['ipv4']['address'] }}"  --pod-network-cidr=10.0.0.0/16
     with_items: "{{ groups['master'] }}"
   
   - name: List kubeadm join command
     shell: kubeadm token create --print-join-command
     register: kubeadm_join

   - name: Set the fact
     set_fact:
      kubeadm_join: "{{ kubeadm_join }}"

- name: Join workers to master
  hosts: workers
  become: yes

  tasks:

  - name: Run kubeadm_join on workers
    debug:
     msg: "{{ hostvars[item]['kubeadm_join'].stdout }}"
    with_items: "{{ groups['master'] }}"

- name: Label nodes
  hosts: master
  
  tasks:

    - name: Apply roles to worker nodes
      shell: kubectl label node "{{ item }}" node-role.kubernetes.io/worker=
      with_items: "{{ groups['workers'] }}"