---
# Playbook for kubernetes install and config

- name: Kubernetes install + config
  hosts: dev
  become: yes
  
  tasks:

    - name: Add Kubernetes repo
      shell: |
       curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
       cat <<EOF | sudo tee /etc/apt/sources.list.d/kubernetes.list
       deb https://apt.kubernetes.io/ kubernetes-xenial main
       EOF

    - name: Install kubeadm stuff
      apt:
        update_cache: yes
        force_apt_get: yes
        pkg:
          - kubeadm
          - kubelet
          - kubectl
    
    - name: Hold back k8s updates
      command: apt-mark hold kubelet kubeadm kubectl

    - name: Setup kubectl for non-root user
      shell: |
        mkdir -p /home/ubuntu/.kube
        cp /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
        chown ubuntu. /home/ubuntu/.kube/config
        export KUBECONFIG=/home/ubuntu/.kube/config
        systemctl daemon-reload
        systemctl restart kubelet

  # Pod network plugin install

- name: Install pod network addon
  hosts: master
  become: yes

  tasks:
   - name: Create NetworkManager conf.d dir
     file:
      path: /etc/NetworkManager/conf.d
      state: directory
      owner: ubuntu
      group: ubuntu
      mode: "0755"
   - name: Create NetworkManager calico.conf
     copy:
      src: /home/theone/projects/ansible/includes/calico.conf
      dest: /etc/NetworkManager/conf.d/calico.conf
      owner: ubuntu
      group: ubuntu
      mode: "0644"
   - name: Acquire and apply Calico manifest
     shell: |
      wget https://docs.projectcalico.org/v3.10/manifests/calico.yaml 
      POD_CIDR="10.0.0.0/16"
      sed -i -e "s?192.168.0.0/16?$POD_CIDR?g" calico.yaml
      kubectl apply -f calico.yaml
      rm calico.yaml
      systemctl daemon-reload
      systemctl restart kubelet