---
# Playbook for kubernetes cluster pre-checks

# TODO add conditional execution to all command/shell/iptables/lineinfile calls
# TODO get non-idempotent vars out of here
- name: Prechecks
  hosts: dev
  become: yes

  tasks:
  
  # Non-shell way? Ansible complains about this
    - name: Add Kubernetes repo
      shell: |
       curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
       cat <<EOF | sudo tee /etc/apt/sources.list.d/kubernetes.list
       deb https://apt.kubernetes.io/ kubernetes-xenial main
       EOF

    - name: Install package dependencies
      apt:
        pkg:
          - iptables
          - arptables
          - ebtables
          - docker.io
          - apt-transport-https
          - curl
          - kubeadm
          - kubelet
          - kubectl
        force_apt_get: yes
        update_cache: yes
    
    - name: Hold back k8s updates
      command: apt-mark hold kubelet kubeadm kubectl 

    - name: Enable services
      command: systemctl enable docker.service

    - name: Update iptables options for kubeadm compatibility
      command: "{{ item }}"
      args:
      with_items:
        - update-alternatives --set iptables /usr/sbin/iptables-legacy
        - update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
        - update-alternatives --set arptables /usr/sbin/arptables-legacy
        - update-alternatives --set ebtables /usr/sbin/ebtables-legacy

- name: Updating firewall rules for master
  hosts: master
  become: yes

  tasks:
    - name: Add iptables rules for master node
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        jump: ACCEPT
      with_items:
        - "6443"
        - "2379:2380"
        - "10250"
        - "10251"
        - "10252"

- name: Updating firewall rules for workers
  hosts: workers
  become: yes

  tasks:
    - name: Add iptables rules for worker nodes
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        jump: ACCEPT
      with_items:
        - "10250"
        - "30000:32767"

- name: Node config tasks
  hosts: dev
  become: yes

  tasks:

    - name: Set default cgroup driver to systemd
      copy:
        src: /home/theone/projects/ansible/includes/docker_daemon.json
        dest: /etc/docker/daemon.json
        owner: ubuntu
        group: ubuntu
        mode: "0644"

    - name: Create dir for docker systemd
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: "0755"

    - name: Setup kubectl for non-root user
      shell: |
        mkdir -p /home/ubuntu/.kube
        cp /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
        chown ubuntu. /home/ubuntu/.kube/config
        export KUBECONFIG=/home/ubuntu/.kube/config
    
    - name: Disable swap
      command: swapoff --all

    - name: Memory cgroup for pi4
      lineinfile:
        path: /boot/firmware/nobtcmd.txt
        regex: "(^.*$)"
        line: net.ifnames=0 dwc_otg.lpm_enable=0 console=ttyAMA0,115200 console=tty1 root=LABEL=writable rootfstype=ext4 elevator=deadline rootwait cgroup_enable=memory cgroup_memory=1
    
    - name: Reboot to apply memory cgroup
      reboot:
