---
# Playbook for kubernetes cluster pre-checks

- name: Prechecks
  hosts: dev

  tasks:
    - name: Disable swap
      command: swapoff --all

    - name: Memory cgroup for pi4
      lineinfile:
        path: /boot/firmware/nobtcmd.txt
        regex: "(^.*$)"
        line: net.ifnames=0 dwc_otg.lpm_enable=0 console=ttyAMA0,115200 console=tty1 root=LABEL=writable rootfstype=ext4 elevator=deadline rootwait cgroup_enable=memory cgroup_memory=1

    - name: Reboot to apply memory cgroup
      reboot:

    # iptables checks start here
    - name: Check if legacy iptables options exist
      apt:
        force_apt_get: yes
        pkg:
          - iptables
          - arptables
          - ebtables

    # Only run this if you have to!
    - name: Update iptables options for kubeadm compatibility
      command: "{{ item }}"
      args:
      with_items:
        - update-alternatives --set iptables /usr/sbin/iptables-legacy
        - update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
        - update-alternatives --set arptables /usr/sbin/arptables-legacy
        - update-alternatives --set ebtables /usr/sbin/ebtables-legacy

- name: Updating firewall rules for master
  hosts: master
  become: yes

  tasks:
    - name: Add iptables rules for master node
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        jump: ACCEPT
      with_items:
        - "6443"
        - "2379:2380"
        - "10250"
        - "10251"
        - "10252"

- name: Updating firewall rules for workers
  hosts: workers
  become: yes

  tasks:
    - name: Add iptables rules for worker nodes
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        jump: ACCEPT
      with_items:
        - "10250"
        - "30000:32767"

# Installing k8s + dependencies

- name: Package installations
  become: yes
  hosts: dev
  tasks:
    - name: Install dependencies
      apt:
        pkg:
          - docker.io
          - apt-transport-https
          - curl
        force_apt_get: yes
        update_cache: yes

    - name: Enable services
      shell: |
        systemctl enable docker.service

    - name: Set default cgroup driver to systemd
      copy:
        src: /home/theone/projects/ansible/includes/docker_daemon.json
        dest: /etc/docker/daemon.json
        owner: ubuntu
        group: ubuntu
        mode: "0644"

    - name: Create dir for docker systemd
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: "0755"