---
- name: Set kubeadm token + kubeadm_join
  hosts: master
  
  tasks:

  - name: List kubeadm join command
    shell: kubeadm token create --print-join-command
    register: kubeadm_join

  - name: Set the fact
    set_fact:
      kubeadm_join: "{{ kubeadm_join }}"

- name: Join workers to master
  hosts: workers
  become: yes

  tasks:

  - name: Run kubeadm_join on workers
    shell: "{{ hostvars['kronos']['kubeadm_join'].stdout }}"