---
# Playbook for deploying kubeadm on target hosts

- name: Kubeadm prechecks
  hosts: dev
  become: yes

  tasks:
    - name: Disable swap
      command: swapoff --all

    # iptables checks start here
    - name: Check if legacy iptables options exist
      apt:
        force_apt_get: yes
        pkg:
          - iptables
          - arptables
          - ebtables
# Only run this if you have to!
#  - name: Update iptables options for kubeadm compatibility
#  command: "{{ item }}"
#  args:
# with_items:
#  - update-alternatives --set iptables /usr/sbin/iptables-legacy
#  - update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
#  - update-alternatives --set arptables /usr/sbin/arptables-legacy
#  - update-alternatives --set ebtables /usr/sbin/ebtables-legacy

- name: Updating firewall rules for master
  hosts: master
  become: yes

  tasks:
    - name: Add iptables rules for master node
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        jump: ACCEPT
      with_items:
        - "6443"
        - "2379:2380"
        - "10250"
        - "10251"
        - "10252"

- name: Updating firewall rules for workers
  hosts: workers
  become: yes

  tasks:
    - name: Add iptables rules for worker nodes
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        jump: ACCEPT
      with_items:
        - "10250"
        - "30000:32767"

# Installing k8s + dependencies

- name: Package installations
  become: yes
  hosts: dev
  tasks:
    - name: Install dependencies
      apt:
        pkg:
          - docker
          - apt-transport-https
          - curl
        force_apt_get: yes

    - name: Add Kubernetes repo
      shell:
      cmd: |
        curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        cat <<EOF | sudo tee /etc/apt/sources.list.d/kubernetes.list
        deb https://apt.kubernetes.io/ kubernetes-xenial main
        EOF

    - name: Install kubeadm stuff
      apt:
        update_cache: yes
        force_apt_get: yes
        pkg:
          - kubeadm
          - kubelet
          - kubectl

    - name: Hold back Kube updates
      command: apt-mark hold kubelet kubeadm kubectl

    - name: Restart kubelet
      shell:
      cmd: |
        systemctl daemon-reload
        systemctl restart kubelet

# Pod Network Plugin install

- name: Install Pod Network Plugin
  hosts: dev
  become: yes

  tasks:
    # iptables setup
    - name: Pass bridged IPv4 traffic to iptables' chains
      command: sysctl net.bridge.bridge-nf-call-iptables=1
    - name: Open TCP 6783 in
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "6783"
        jump: ACCEPT
    - name: Open TCP 6783 out
      iptables:
        chain: OUTPUT
        protocol: tcp
        destination_port: "6783"
        jump: ACCEPT
    - name: Open UDP 6783/6784 in
      iptables:
        chain: INPUT
        protocol: udp
        destination_port: "6783:6784"
        jump: ACCEPT
    - name: Open UDP 6783/6784 out
      iptables:
        chain: OUTPUT
        protocol: udp
        destination_port: "6783:6784"
        jump: ACCEPT
    # weave installation
    - name: Install Weave Net
      shell:
      cmd: |
        kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
    # portmap setup
    - name: Install portmap binary to /opt/cni/bin/portmap
      shell:
      cmd: |
        git clone https://github.com/containernetworking/plugins
        cd plugins
        ./build.sh
        cp bin/* /opt/cni/bin/
    - name: Copy portmap config to /etc/cni/net.d/10-weave.conflist
      copy:
        src: /home/theone/projects/ansible/includes/10-weave.conflist
        dest: /etc/cni/net.d/10-weave.conflist
        owner: ubuntu
        group: ubuntu
        mode: "0644"

- name: Initialize control plane node
  hosts: master
  become: yes

  tasks:
    - name: Verify connectivity to registry
      command: kubeadm config images pull

    - name: Initialize master node
      command: kubeadm init --control-plane-endpoint=192.168.0.102 kronos --node-name master
      register: init_output

    - name: Setup kubectl for non-root user
      shell:
      cmd: |
        mkdir -p $HOME/.kube
        cp /etc/kubernetes/admin.conf $HOME/.kube/config
        chown ubuntu. $HOME/.kube/config
          
           # kubelet --network-plugin=portmap
