---
- name: Resets k8s env for cluster
  hosts: dev
  become: yes
  
  tasks:
   - name: Flush iptables rules
     iptables:
      chain: "{{ item }}"
      flush: yes
     with_items:  [ 'INPUT', 'FORWARD', 'OUTPUT' ]
   - name: Flush iptables nat
     iptables:
      table: nat
      chain: '{{ item }}'
      flush: yes
     with_items: [ 'INPUT', 'OUTPUT', 'PREROUTING', 'POSTROUTING' ]
   - name: Flush iptables mangle
     iptables:
      table: mangle
      chain: '{{ item }}'
      flush: yes
     with_items: [ 'INPUT', 'OUTPUT', 'PREROUTING', 'POSTROUTING' ]

- name: Remove config stuff
  hosts: dev
  become: yes

  tasks:
   - name: Remove network configs + plugins
     file:
      path: "{{ item }}"
      state: absent
     with_items:
      - /etc/cni/net.d/10-weave.conflist
      - /etc/NetworkManager/conf.d
      - /opt/cni/bin
      - /home/ubuntu/.kube

- name: Shuts down master node
  hosts: master
  become: yes

  tasks:
   - name: Drain master node
     shell: |
      kubectl drain "{{ ansible_host }}" --delete-local-data --force --ignore-daemonsets

   - name: Delete master node
     command: kubectl delete node "{{ ansible_host }}"

   - name: Kubeadm reset
     command: kubeadm reset