---
- name: Resets k8s env for cluster
  hosts: dev
  become: yes
  
  tasks:
   - name: Flush iptables rules
     iptables:
      chain: "{{ item }}"
      flush: yes
     with_items:  [ 'INPUT', 'FORWARD', 'OUTPUT' ]

#   - name: Tear down any existing nodes + k8s configs

#   - name: Remove network plugin stuff