---
# Adds arbitrary user to arbitrary host

- hosts: all
  become: yes
  tasks:
    - name: Create the user
      user: name="{{ user_name }}" append=yes state=present createhome=yes shell=/bin/bash

    - name: Allow user to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: '"{{ user_name }}" ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Set up authorized keys for the user
      authorized_key: user="{{ user_name }}" key="{{ item }}"
      with_file:
        - ~/.ssh/"{{ ansible_host }}".key.pub